# .cpanel.yml
deployment:
  tasks:
    - export REPO_DIR=$(pwd)
    - export PUBLIC_DIR=/home2/Julio861/public_html

    # Instalar dependências
    - 'if [ -f yarn.lock ]; then /usr/local/bin/yarn install --frozen-lockfile; else /usr/local/bin/npm ci --no-audit --no-fund; fi'

    # Build de produção (Vite)
    - 'if [ -f yarn.lock ]; then CI=false /usr/local/bin/yarn build; else CI=false /usr/local/bin/npm run build; fi'

    # Apagar conteúdo antigo
    - /bin/rm -rf $PUBLIC_DIR/*

    # Copiar dist/ para public_html
    - /bin/cp -R $REPO_DIR/dist/* $PUBLIC_DIR/

    # Garantir que o .htaccess seja copiado
    - 'if [ -f .htaccess ]; then /bin/cp .htaccess $PUBLIC_DIR/.htaccess; fi'
